[tool.poetry]
name = "pytest_httpserver"
version = "1.0.6"
description = "pytest-httpserver is a httpserver for pytest"
authors = ["Zsolt Cserna <cserna.zsolt@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://pytest-httpserver.readthedocs.io/en/latest/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Framework :: Pytest",
]
repository = "https://github.com/csernazs/pytest-httpserver"

include = [
    { path = "tests", format = "sdist" },
    { path = "CHANGES.rst", format = "sdist" },
    { path = "CONTRIBUTION.md", format = "sdist" },
    { path = "example*.py", format = "sdist" },
    { path = "doc", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
Werkzeug = ">= 2.0.0"


[tool.poetry.plugins.pytest11]
pytest_httpserver = "pytest_httpserver.pytest_plugin"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/csernazs/pytest-httpserver/issues"

[tool.poetry.group.develop]
optional = true

[tool.poetry.group.develop.dependencies]
pre-commit = "^2.20.0"
requests = "^2.28.1"
Sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"
reno = "^3.5.0"
mypy = "^0.971"
types-requests = "^2.28.9"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
coverage = "^6.4.4"
ipdb = "^0.13.9"
types-toml = "^0.10.8"


[tool.poetry.group.doc]
optional = true

[tool.poetry.group.doc.dependencies]
Sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"


[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
coverage = "^6.4.4"
requests = "^2.28.1"
mypy = "^0.971"
types-requests = "^2.28.9"
pre-commit = "^2.20.0"
types-toml = "^0.10.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "ssl: set up ssl context",
    "release: run release tests",
]

[tool.mypy]
files = ["pytest_httpserver", "scripts", "tests", "doc"]
implicit_reexport = false
